const launchOpts=require('./launch');
const puppeteer=require('puppeteer-core');
(async()=>{
  const browser=await puppeteer.launch(await launchOpts());
  const page=await browser.newPage(); const errs=[]; page.on('pageerror',e=>errs.push('PAGEERR '+e.message));
  await page.setViewport({width:390,height:780,isMobile:true,hasTouch:true});
  await page.goto('file://'+require('path').resolve(__dirname,'../dist/game.html'),{waitUntil:'load'});
  await page.evaluate(()=>localStorage.clear()); await page.reload({waitUntil:'load'});
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const click=async s=>{ await page.click(s); await sleep(50); };
  const txt=()=>page.evaluate(()=>document.querySelector('#app').innerText.replace(/\s+/g,' '));
  const has=async(sel)=>page.evaluate(s=>!!document.querySelector(s),sel);
  const imgOk=async(sel)=>page.evaluate(s=>{ const i=document.querySelector(s); return !!i&&i.src.startsWith('data:image/png;base64,')&&i.src.length>500; },sel);
  let fails=0; const T=async(n,f)=>{ try{ const r=await f(); if(r===false) throw new Error('false'); console.log('ok  ',n); }catch(e){ fails++; console.log('FAIL',n,e.message); } };
  await T('title text',async()=>/트로네 공작가의/.test(await txt()));
  await T('title pixel image',()=>imgOk('.title img.bgsvg'));
  await T('title settings',async()=>{ await click('[data-act=titleSettings]'); const ok=/읽기 설정/.test(await txt()); await click('[data-act=backTitle]'); return ok; });
  await T('new game + stage image',async()=>{ await click('[data-act=new]'); return await imgOk('.stage img')&&/도착했습니다/.test(await txt()); });
  await T('notice',async()=>{ await click('[data-act=notice]'); return has('.jot'); });
  await T('choice flows',async()=>{ await click('[data-act=choice]'); if(!/마로트라고 합니다/.test(await txt())) return false; await click('[data-act=choice][data-i="0"]'); return /물어도 되는 일인지/.test(await txt()); });
  await T('walk to end card',async()=>{ for(let i=0;i<70;i++){ const ids=await page.evaluate(()=>[...document.querySelectorAll('[data-act=notice]')].map(e=>e.dataset.id)); for(const id of ids) await click(`[data-id=${id}]`); if(await has('.endcard')) break; const c=await page.$('[data-act=choice]'); if(!c) break; await click('[data-act=choice]'); } return has('.endcard'); });
  await T('conditional choices (hands)',async()=>{ const r=await page.evaluate(()=>{ S.noticed={}; S.flags={}; S.scene='c3c'; draw(); const a=document.querySelectorAll('.choice').length; S.noticed={hands:1}; draw(); const b=document.querySelectorAll('.choice').length; return [a,b]; }); return r[0]===1&&r[1]===2; });
  await T('clock note changes Holt',async()=>{ const r=await page.evaluate(()=>{ S.noticed={}; S.flags={}; S.scene='c2f'; draw(); const a=document.querySelector('.textbox').innerText.includes('회중시계'); S.noticed={clock:1}; draw(); const b=document.querySelector('.textbox').innerText.includes('회중시계'); return [a,b]; }); return r[0]===false&&r[1]===true; });
  await T('notebook shows player notes',async()=>{ return page.evaluate(()=>{ S.noticed={lie:1,curtain:2}; S.flags={}; S.scene='c2d'; draw(); return document.querySelectorAll('.textbox .jot').length===2; }); });
  await T('full playthrough ch1-4 reaches end',async()=>{ await page.evaluate(()=>{ localStorage.clear(); S=freshSave(); persist(); ui={screen:'game',tab:null,sub:'root'}; draw(); }); for(let i=0;i<70;i++){ const ids=await page.evaluate(()=>[...document.querySelectorAll('[data-act=notice]')].map(e=>e.dataset.id)); for(const id of ids) await click('[data-id='+id+']'); if(await has('.endcard')) break; const c=await page.$('[data-act=choice]'); if(!c) break; await click('[data-act=choice]'); } return (await has('.endcard'))&&/1권 4장까지/.test(await txt()); });
  await T('ch4 sugar branch changes Marot',async()=>page.evaluate(()=>{ const keep=JSON.stringify(S); S.noticed={}; S.flags={sugar:1,noTell:1}; S.scene='c4e'; draw(); const t1=document.querySelector('.textbox').innerText; S.flags={noSugar:1,mayTell:1}; draw(); const t2=document.querySelector('.textbox').innerText; const r=/넣지 않으셔도 됩니다/.test(t1)&&/원하지 않아요/.test(t1)&&/이미 넣지 않으셨더군요/.test(t2)&&/물으시기 전에는/.test(t2)&&!/넣지 않으셔도 됩니다/.test(t2); S=JSON.parse(keep); draw(); return r; }));
  await T('ch4 notebook shows ch4 notes only',async()=>page.evaluate(()=>{ const keep=JSON.stringify(S); S.noticed={lie:1,pen:2,spoon:3}; S.flags={askedWhose:1}; S.scene='c4h'; draw(); const j=[...document.querySelectorAll('.textbox .jot')].map(e=>e.innerText); S.noticed={lie:1}; draw(); const e=/적지 못했다/.test(document.querySelector('.textbox').innerText); S=JSON.parse(keep); draw(); return j.length===2&&e; }));
  await T('quick theme button cycles light-paper-dark',async()=>{ await page.evaluate(()=>{ pref.theme='light'; pref.dim=0; applyPref(); ui.tab=null; draw(); }); const seq=[]; for(let i=0;i<3;i++){ await click('[data-act=qtheme]'); seq.push(await page.evaluate(()=>document.documentElement.getAttribute('data-theme'))); } await page.evaluate(()=>{ pref.theme='auto'; applyPref(); draw(); }); return seq.join(',')==='paper,dark,light'; });
  await T('every scene image ok',async()=>page.evaluate(()=>Object.keys(SCENES).every(k=>{ const s=SCENES[k]; const h=stageSVG(s.place,s.season,s.chars,s.time); return h.includes('data:image/png;base64,'); })));
  await T('notes >=7',async()=>{ await click('[data-tab=notes]'); return (await page.evaluate(()=>document.querySelectorAll('.panel .jot').length))>=7; });
  await T('letters',async()=>{ await click('[data-tab=letters]'); return /아직 편지가 없어요/.test(await txt()); });
  await T('mansion 9 images',async()=>{ await click('[data-tab=mansion]'); return (await page.evaluate(()=>[...document.querySelectorAll('.place img')].filter(i=>i.src.length>500).length))===9; });
  await T('settings root',async()=>{ await click('[data-tab=settings]'); return /이야기 서재/.test(await txt()); });
  await T('font+theme',async()=>{ await click('[data-act=sub][data-v=reading]'); await click('[data-act=fs][data-v="1"]'); const a=/19px/.test(await txt()); await click('[data-act=theme][data-v=dark]'); const b=await page.evaluate(()=>document.documentElement.getAttribute('data-theme')==='dark'); await click('[data-act=theme][data-v=auto]'); await click('[data-act=sub][data-v=root]'); return a&&b; });
  await T('save code roundtrip',async()=>{ await click('[data-act=sub][data-v=save]'); await click('[data-act=toggleCode]'); const code=await page.evaluate(()=>document.querySelector('#codeOut').value); await page.evaluate(c=>{ document.querySelector('#codeIn').value=c; },code); await click('[data-act=importCode]'); const ok=/불러왔어요/.test(await txt()); await click('[data-act=sub][data-v=root]'); return ok; });
  await T('library 37',async()=>{ await click('[data-act=sub][data-v=library]'); return (await page.evaluate(()=>document.querySelectorAll('.toc .it').length))===37; });
  await T('reader ch1 next',async()=>{ await click('[data-act=chap][data-n="1"]'); if(!/마차가 멈췄을 때/.test(await txt())) return false; const b=await page.$$('.pager button'); await b[1].click(); await sleep(60); return /가정교사의 첫 수업/.test(await txt()); });
  await T('ch30 forks',async()=>{ await click('[data-act=sub][data-v=library]'); await click('[data-act=chap][data-n="30"]'); if((await page.evaluate(()=>document.querySelectorAll('.fb').length))!==9) return false; await click('[data-act=branch][data-id=hadel]'); return /춥다/.test(await page.evaluate(()=>document.querySelector('#epi').innerText)); });
  await T('extra 7',async()=>{ await click('[data-act=sub][data-v=library]'); await click('[data-act=chap][data-n="37"]'); return /서재의 불/.test(await txt()); });
  await T('characters 16 images',async()=>{ await click('[data-act=sub][data-v=library]'); await click('[data-act=sub][data-v=root]'); await click('[data-act=sub][data-v=chars]'); return (await page.evaluate(()=>[...document.querySelectorAll('.chr img')].filter(i=>i.src.length>500).length))===16; });
  await T('close tab',async()=>{ await click('[data-act=sub][data-v=root]'); await click('[data-act=closeTab]'); return !(await has('.panel')); });
  await T('continue after reload',async()=>{ await page.reload({waitUntil:'load'}); if(!/이어하기/.test(await txt())) return false; await click('[data-act=continue]'); return has('.stage img'); });
  await T('end-card restart confirm',async()=>{ await page.evaluate(()=>{ S.scene='send'; persist(); draw(); }); await sleep(40); await click('[data-act=choice][data-i="2"]'); const c=/지워져요/.test(await txt()); await click('[data-act=endNo]'); const k=await has('.endcard'); return c&&k; });
  console.log(errs.length?('PAGE ERRORS: '+errs.join(' | ')):'no page errors');
  console.log(fails?('FAILED '+fails):'ALL PASSED');
  await browser.close();
})();
